FROM node:latest-alpine

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
COPY tsconfig.json ./

RUN npm install
RUN npm install -g typescript

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]