name: CI/CD Pipeline for Dev Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Add directory to PATH
        run: echo "/home/dev_mono/.nvm/versions/node/v22.15.0/bin/pm2" >> $GITHUB_PATH

      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_KEY }}
          port: 22
          script: |
            cd dev_mono_app
            git pull origin main
            cd
            pm2 restart all
