name: CI/CD Pipeline for Dev Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          port: 22
          script: |
            # Add your production deployment commands here
            echo "Deploying to production server..."
            # Example: npm install && npm run build
            # Example: pm2 restart all
            echo "Deployment complete!"
            cd /prod_mono
            ls -la